- name: Temp clone git project to get commit id
  git:
    repo: "{{ upstream }}"
    clone: no
  register: result_git

- block:

  - name: send failure notification via telegram
    tags: always
    telegram:
      token: "{{ telegram_token }}"
      api_args:
        chat_id: "{{ telegram_chat_id }}"
        parse_mode: "markdown"
        text: "âš ï¸  Ansible provision failed on *{{ ansible_hostname }}*\n\n
          *Task*:  {{ ansible_failed_task.name }}\n
          # *Action*: {{ ansible_failed_task.action }}\n
          # *Revision*: [failed commit revision]({{ upstream }}/commit/{{ result_git.before }})\n
          # *Error Message*: \n ```{{  ansible_failed_result.msg }}```"
          # *Action*: {{ ansible_failed_task.action }}"
          # *Error Message*: \n ```{{ ansible_failed_result | to_nice_json }}```"
    changed_when: False

  rescue:
    - name: send failure notification via telegram
      tags: always
      telegram:
        token: "{{ telegram_token }}"
        api_args:
          chat_id: "{{ telegram_chat_id }}"
          parse_mode: "markdown"
          text: "ðŸš© *{{ ansible_hostname }}* provision failed.\n\n[failed commit revision]({{ upstream }}/commit/{{ result_git.before }})"
      changed_when: False

- name: ansible job failed, clear cache later on to trigger another provision run
  become: yes
  at:
    command: "if ! pgrep -f ansible-pull >/dev/null; then rm -rf /home/tg/.ansible; fi"
    count: 60
    units: minutes
